// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorTemplates.Models;

#nullable disable

namespace RazorTemplates.Migrations.Ticket
{
    [DbContext(typeof(TicketContext))]
    [Migration("20260408020223_AddTicketSeedData")]
    partial class AddTicketSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorTemplates.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "todo",
                            StatusName = "To Do"
                        },
                        new
                        {
                            StatusId = "inprogress",
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusId = "qa",
                            StatusName = "Quality Assurance"
                        },
                        new
                        {
                            StatusId = "done",
                            StatusName = "Done"
                        });
                });

            modelBuilder.Entity("RazorTemplates.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("PointValue")
                        .HasColumnType("int");

                    b.Property<int>("SprintNumber")
                        .HasColumnType("int");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            PointValue = 5,
                            SprintNumber = 1,
                            StatusId = "done",
                            TicketDescription = "Build Controllers for project",
                            TicketName = "Build Controllers"
                        },
                        new
                        {
                            TicketId = 2,
                            PointValue = 10,
                            SprintNumber = 2,
                            StatusId = "todo",
                            TicketDescription = "Code all models for project",
                            TicketName = "Build Models"
                        },
                        new
                        {
                            TicketId = 3,
                            PointValue = 8,
                            SprintNumber = 3,
                            StatusId = "todo",
                            TicketDescription = "Code Program.cs in project",
                            TicketName = "Complete Program.cs"
                        },
                        new
                        {
                            TicketId = 4,
                            PointValue = 5,
                            SprintNumber = 3,
                            StatusId = "inprogress",
                            TicketDescription = "Make images folder and add images",
                            TicketName = "Images Folder"
                        },
                        new
                        {
                            TicketId = 5,
                            PointValue = 10,
                            SprintNumber = 4,
                            StatusId = "qa",
                            TicketDescription = "Code unit tests for project",
                            TicketName = "Unit Testing"
                        });
                });

            modelBuilder.Entity("RazorTemplates.Models.Ticket", b =>
                {
                    b.HasOne("RazorTemplates.Models.Status", "status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("status");
                });
#pragma warning restore 612, 618
        }
    }
}
