// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorTemplates.Models;

#nullable disable

namespace RazorTemplates.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorTemplates.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "curling",
                            CategoryName = "Curling/Indoor"
                        },
                        new
                        {
                            CategoryId = "bobsleigh",
                            CategoryName = "Bobsleigh/Outdoor"
                        },
                        new
                        {
                            CategoryId = "diving",
                            CategoryName = "Diving/Indoor"
                        },
                        new
                        {
                            CategoryId = "cycling",
                            CategoryName = "Road Cycling/Outdoor"
                        },
                        new
                        {
                            CategoryId = "archery",
                            CategoryName = "Archery/Indoor"
                        },
                        new
                        {
                            CategoryId = "canoe",
                            CategoryName = "Canoe Sprint/Outdoor"
                        },
                        new
                        {
                            CategoryId = "breakdancing",
                            CategoryName = "Breakdancing/Indoor"
                        },
                        new
                        {
                            CategoryId = "skateboarding",
                            CategoryName = "Skateboarding/Outdoor"
                        });
                });

            modelBuilder.Entity("RazorTemplates.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "can",
                            CategoryId = "curling",
                            CountryFlag = "CAN.png",
                            CountryName = "Canada",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "swe",
                            CategoryId = "curling",
                            CountryFlag = "SWE.png",
                            CountryName = "Sweden",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "bri",
                            CategoryId = "curling",
                            CountryFlag = "BRI.png",
                            CountryName = "Great Britain",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "jam",
                            CategoryId = "bobsleigh",
                            CountryFlag = "JAM.png",
                            CountryName = "Jamaica",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "ita",
                            CategoryId = "bobsleigh",
                            CountryFlag = "ITA.png",
                            CountryName = "Italy",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "jap",
                            CategoryId = "bobsleigh",
                            CountryFlag = "JAP.png",
                            CountryName = "Japan",
                            GameId = "win"
                        },
                        new
                        {
                            CountryId = "ger",
                            CategoryId = "diving",
                            CountryFlag = "GER.png",
                            CountryName = "Germany",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "chi",
                            CategoryId = "diving",
                            CountryFlag = "CHI.png",
                            CountryName = "China",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "mex",
                            CategoryId = "diving",
                            CountryFlag = "MEX.png",
                            CountryName = "Mexico",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "bra",
                            CategoryId = "cycling",
                            CountryFlag = "BRA.png",
                            CountryName = "Brazil",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "net",
                            CategoryId = "cycling",
                            CountryFlag = "NET.png",
                            CountryName = "Netherlands",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "usa",
                            CategoryId = "cycling",
                            CountryFlag = "USA.png",
                            CountryName = "USA",
                            GameId = "sum"
                        },
                        new
                        {
                            CountryId = "tha",
                            CategoryId = "archery",
                            CountryFlag = "THA.png",
                            CountryName = "Thailand",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "uru",
                            CategoryId = "archery",
                            CountryFlag = "URU.png",
                            CountryName = "Uruguay",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "ukr",
                            CategoryId = "archery",
                            CountryFlag = "UKR.png",
                            CountryName = "Ukraine",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "aus",
                            CategoryId = "canoe",
                            CountryFlag = "AUS.png",
                            CountryName = "Austria",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "pak",
                            CategoryId = "canoe",
                            CountryFlag = "PAK.png",
                            CountryName = "Pakistan",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "zim",
                            CategoryId = "canoe",
                            CountryFlag = "ZIM.png",
                            CountryName = "Zimbabwe",
                            GameId = "para"
                        },
                        new
                        {
                            CountryId = "fra",
                            CategoryId = "breakdancing",
                            CountryFlag = "FRA.png",
                            CountryName = "France",
                            GameId = "youth"
                        },
                        new
                        {
                            CountryId = "cyp",
                            CategoryId = "breakdancing",
                            CountryFlag = "CYP.png",
                            CountryName = "Cyprus",
                            GameId = "youth"
                        },
                        new
                        {
                            CountryId = "rus",
                            CategoryId = "breakdancing",
                            CountryFlag = "RUS.png",
                            CountryName = "Russia",
                            GameId = "youth"
                        },
                        new
                        {
                            CountryId = "fin",
                            CategoryId = "skateboarding",
                            CountryFlag = "FIN.png",
                            CountryName = "Finland",
                            GameId = "youth"
                        },
                        new
                        {
                            CountryId = "slo",
                            CategoryId = "skateboarding",
                            CountryFlag = "SLO.png",
                            CountryName = "Slovakia",
                            GameId = "youth"
                        },
                        new
                        {
                            CountryId = "por",
                            CategoryId = "skateboarding",
                            CountryFlag = "POR.png",
                            CountryName = "Portugal",
                            GameId = "youth"
                        });
                });

            modelBuilder.Entity("RazorTemplates.Models.Game", b =>
                {
                    b.Property<string>("GameId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = "win",
                            GameName = "Winter Olympics"
                        },
                        new
                        {
                            GameId = "sum",
                            GameName = "Summer Olympics"
                        },
                        new
                        {
                            GameId = "para",
                            GameName = "Paralymics"
                        },
                        new
                        {
                            GameId = "youth",
                            GameName = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("RazorTemplates.Models.Country", b =>
                {
                    b.HasOne("RazorTemplates.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazorTemplates.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.Navigation("Category");

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
